### ISSUE TITLE
qmtools complains about tsv path

### ISSUE THREAD

**Issue by Diheng** [hickst/qmtools-support#3]
I tried to run the qmtools with the tutorial (https://bitbucket.org/dpat/neuro4rii/raw/main/cloudshell_lessons/tutorial_qmtools.md) and the qmviolin and qmtraffic complain about path to the tsv files:

```
dihengzhang@cloudshell:~/qmtest$ ./qmtraffic bold inputs/sample_bold.tsv -r sample_bold_traffic
(qmtraffic): ERROR: A path to a readable, MRIQC group file (.tsv) must be specified. Exiting...
```

ENV:
Google shell with docker

**Comment by dkp** [comment]
@Diheng 
It seems like you have an old copy of the tutorial (After our refactoring, the qmtest directory is no longer mentioned. Instead the qmtools-support directory is specified.  We also renamed some of the sample files to be more consistent).  I just ran the entire tutorial on google cloudshell and it worked well.  Try starting fresh with the qmtools-support directory and the updated tutorial (3/9).

**Comment by Diheng** [comment]
> @Diheng
> It seems like you have an old copy of the tutorial (After our refactoring, the qmtest directory is no longer mentioned. Instead the qmtools-support directory is specified. We also renamed some of the sample files to be more consistent). I just ran the entire tutorial on google cloudshell and it worked well. Try starting fresh with the qmtools-support directory and the updated tutorial (3/9).

Thanks for pointing that out. I git clone the newer qmtools-support directory and it is working now. Cheers!
